//LEAGUES ACTION TYPES
export const GET_LEAGUES_REQUEST = "GET_LEAGUES_REQUEST";
export const GET_LEAGUES_SUCCESS = "GET_LEAGUES_SUCCESS";
export const GET_LEAGUES_ERROR = "GET_LEAGUES_ERROR";

export const GET_LEAGUE_REQUEST = "GET_LEAGUE_REQUEST";
export const GET_LEAGUE_SUCCESS = "GET_LEAGUE_SUCCESS";
export const GET_LEAGUE_ERROR = "GET_LEAGUE_ERROR";

//TEAMS ACTION TYPES
export const GET_TEAMS_REQUEST = "GET_TEAMS_REQUEST";
export const GET_TEAMS_SUCCESS = "GET_TEAMS_SUCCESS";
export const GET_TEAMS_ERROR = "GET_TEAMS_ERROR";
